* Building a FreeBSD image for the arm64 ESPRESSObin

One of the nicest things about *BSD systems is that the OS and kernel are maintained in tandem. And
all of the BSD's have tooling in place in their build system for cross compiling the system for
another architecture. This is fantastic as it means less work for us. This would be a great place to
start but we've chosen to use FreeBSD, and so things just got even simpler! We have
crochet. [[https://github.com/theasylum/crochet.git][Crochet]], specifically is the repo we're using, the upstream is available [[https://github.com/freebsd/crochet][here]]. Crochet
makes building our image a snap, so given that, here we go for fun and profit!

*** First let's go ahead and prep our system

I'll assume you don't have any of the sources, so let's go ahead and set that up. There are many
many ways to do this, svn, git, etc. I'm writing this on a FreeBSD 12-CURRENT machine, on
r344651. I'll just use the souces from that snapshot for my purposes.

#+BEGIN_SRC sh
cd /tmp
fetch ftp://ftp.freebsd.org/pub/FreeBSD/snapshots/arm64/12-STABLE/src.txz
tar -Jxf src.txz -C /
#+END_SRC

Now we can go in and get things rolling. I like to seed my system with all the cross compilers I'm
likely to need for whatever I'm building. In this case it's getting ready for arm64/aarch64 cross
compilation, so let's do that:

#+BEGIN_SRC sh
cd /usr/src
env TARGET=arm64 TARGET_ARCH=aarch64 make -j`sysctl hw.ncpu | awk '{print $2}'` xdev
#+END_SRC
