* Building a FreeBSD image for the arm64 ESPRESSObin

One of the nicest things about *BSD systems is that the OS and kernel are maintained in tandem. And
all of the BSD's have tooling in place in their build system for cross compiling the system for
another architecture. This is fantastic as it means less work for us. This would be a great place to
start but we've chosen to use FreeBSD, and so things just got even simpler! We have
crochet. [[https://github.com/theasylum/crochet.git][Crochet]], specifically is the repo we're using, the upstream is available [[https://github.com/freebsd/crochet][here]]. Crochet
makes building our image a snap, so given that, here we go for fun and profit!

*** First let's go ahead and prep our system

I'll assume you don't have any of the sources, so let's go ahead and set that up. There are many
many ways to do this, svn, git, etc. I'm writing this on a FreeBSD 12-CURRENT machine, on
r344651. I'll just use the souces from that snapshot for my purposes.

#+BEGIN_SRC sh
cd /tmp
fetch ftp://ftp.freebsd.org/pub/FreeBSD/snapshots/arm64/12-STABLE/src.txz
tar -Jxf src.txz -C /
#+END_SRC

Now we can go in and get things rolling. I like to seed my system with all the cross compilers I'm
likely to need for whatever I'm building. In this case it's getting ready for arm64/aarch64 cross
compilation, so let's do that:

#+BEGIN_SRC sh
cd /usr/src
env TARGET=arm64 TARGET_ARCH=aarch64 make -DNO_CLEAN -j`sysctl hw.ncpu | awk '{print $2}'` xdev
#+END_SRC

And just to keep things nice and clean, let's go ahead and create a new home for our crochet
builds. I use ZFS personally, so adjust to suit your needs and setup of course. Once we create our
home, we'll want to check out our crochet repo and get to building

#+BEGIN_SRC sh
zfs create -o mountpoint=/usr/crochet zpool/crochet
cd /usr/crochet
git clone https://github.com/theasylum/crochet.git
cd crochet
cp config.sh.sample espressobin.sh
#+END_SRC

Now we're going to pause here, and take a moment to fix up our espressobin.sh. At a minimum we need
only specify the board (in our case: ESPRESSObin) but, I like to seed the system with enough to make
it useful off the bat. Namely ports and the src that the system was built from. So let's get those
changes made to the config before we kick things off.
