* Building a FreeBSD image for the arm64 ESPRESSObin

One of the nicest things about *BSD systems is that the OS and kernel are maintained in tandem. And
all of the BSD's have tooling in place in their build system for cross compiling the system for
another architecture. This is fantastic as it means less work for us. This would be a great place to
start but we've chosen to use FreeBSD, and so things just got even simpler! We have
crochet. [[https://github.com/theasylum/crochet.git][Crochet]], specifically is the repo we're using, the upstream is available [[https://github.com/freebsd/crochet][here]]. Crochet
makes building our image a snap, so given that, here we go for fun and profit!

*** First let's go ahead and prep our system

I'll assume you don't have any of the sources, so let's go ahead and set that up. There are many
many ways to do this, svn, git, etc. I'm writing this on a FreeBSD 12-CURRENT machine, on
r344651. I'll just use the souces from that snapshot for my purposes.

#+BEGIN_SRC sh
cd /tmp
fetch ftp://ftp.freebsd.org/pub/FreeBSD/snapshots/arm64/12-STABLE/src.txz
tar -Jxf src.txz -C /
#+END_SRC

Now we can go in and get things rolling. I like to seed my system with all the cross compilers I'm
likely to need for whatever I'm building. In this case it's getting ready for arm64/aarch64 cross
compilation, so let's do that:

#+BEGIN_SRC sh
cd /usr/src
env TARGET=arm64 TARGET_ARCH=aarch64 make -DNO_CLEAN -j`sysctl hw.ncpu | awk '{print $2}'` toolchain
#+END_SRC

And just to keep things nice and clean, let's go ahead and create a new home for our crochet
builds. I use ZFS personally, so adjust to suit your needs and setup of course. Once we create our
home, we'll want to check out our crochet repo and get to building

#+BEGIN_SRC sh
zfs create -o mountpoint=/usr/crochet zpool/crochet
#+END_SRC

*** Now let's get Crochet set up

Easy enough, it's a very simple procedure, which is outlined in greated detail in the README so I
won't go into it here. This article is a quick how I did it, not a deep-dive. That being said, do
this:

#+BEGIN_SRC sh
cd /usr/crochet
git clone https://github.com/theasylum/crochet.git
cd crochet
cp config.sh.sample espressobin.sh
#+END_SRC

Now we're going to pause here, and take a moment to fix up our espressobin.sh. At a minimum we need
only specify the board (in our case: ESPRESSObin) but, I like to seed the system with enough to make
it useful off the bat. Namely ports and the src that the system was built from. So let's get those
changes made to the config before we kick things off.

#+BEGIN_SRC sh
board_setup ESPRESSObin
option ImageSize 8092mb
option Growfs
option Email user@domain.tld
option User fuzzy # password will be same as the username
option SwapFile 128mb deferred
option UsrPorts
option UsrSrc
option Ntpd
FREEBSD_INSTALL_WORLD=y
WORLDJOBS="`sysctl hw.ncpu|awk '{print $2}'`"
KERNJOBS="`sysctl hw.ncpu|awk '{print $2}'`"
FREEBSD_EXTRA_ARGS="-DNO_CLEAN"
#+END_SRC

Now, we are obviously not doing anything interesting with this. We could go into the board overlay
and add configuration files, we can initialize the pkg manager and install other packages via the
config file. All kinds of other things, read through config.sh-sample in the crochet checkout for
more information. For now we'll skip on to building our image which is suitable to log into and
start configuring for whatever purpose. If this is enough for you, neat.

#+BEGIN_SRC sh
sudo ./crochet.sh -c espressobin.sh -v
#+END_SRC

That's it. That if it finishes properly, will result in an image named something like:

#+BEGIN
FreeBSD-aarch64-12-GENERIC-ESPRESSObin.img
#+END

Which you can then write to an sd card like:

#+BEGIN_SRC sh
sudo dd if=FreeBSD-aarch64-12-GENERIC-ESPRESSObin.img bs=1m of=/dev/da0 # <- change that to match your system
#+END_SRC

And voila!
